apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-react-headless-moodle-ingress
  labels:
    app: frontend-react-headless-moodle
  annotations:
    kubernetes.io/ingress.class: "gce"
    # kubernetes.io/ingress.global-static-ip-name: "your-static-ip-name"  # Uncomment and set if you have a static IP
    # networking.gke.io/managed-certificates: "your-cert-name"  # Uncomment and set for HTTPS
    kubernetes.io/ingress.allow-http: "true"
spec:
  defaultBackend:
    service:
      name: frontend-react-headless-moodle-service
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-react-headless-moodle-service
            port:
              number: 80
